= Werval 0.5.0 is out!
Werval 0.5.0
2014-12-14
:jbake-type: post
:jbake-status: published
:jbake-tags: announcement
:idprefix:

Following the link:2014-11-28_release_0.4.0.html[0.4.0] release, here is `0.5.0`.
This release is the first under the new project name `werval`.

One feature was added along the way: a link:../doc/current/modules/sanitize/index.html[Sanitize] module that provide utilities for input/output sanitization and encoding thanks to several OWASP projects.

Werval is an open source JVM based toolkit for building HTTP services.
A lightweight core, live reload dev mode, useful modules, plugins for several build tools and
multiple languages support leave you free to choose the right architecture for your domain.

link:../doc/current/get-started-gradle.html[Get started using Gradle]

link:../doc/current/get-started-maven.html[Get started using maven]

Keep in sight that this is an early access release and that some edges may still be rough.

If you encounter any issue, please report by creating a
link:https://github.com/werval/werval/issues/new[new issue].
