= Samples
:jbake-type: page
:jbake-status: published
:jbake-tags: samples
:idprefix:
:toc: right
:toc-title: Samples

Sample applications leveraging the Werval toolset, documented, ready to run, deploy and hack!

NOTE: If you happend to build a sample application and are kin to link:../community.html[contribute] it, we'll be more than happy!


toc::[]

== Overview

All samples applications use the Gradle build system. Here are some tasks common to all of them:

.Run in developement mode
----
gradle devshell
----

.Run in production mode
----
gradle start
----

.Run tests
----
gradle check
----

.Create distribution
----
gradle distZip
----

See their respective READMEs for more.


== URL Shortener

_URL Shortener_ is a simple application using only Werval core.
It operates in-memory and only use the link:../doc/current/modules/json/index.html[JSON module].

See https://github.com/werval/werval-sample-urlshortener

.Clone the project
----
git clone git@github.com:werval/werval-sample-urlshortener.git
----



== Beer Database

_Beer Database_ is a full-featured ReSTful endpoint enlightened by a single page application built using Angular.
Persistence is implemented using the link:../doc/current/modules/jpa/index.html[JPA module].

See https://github.com/werval/werval-sample-beerdb

.Clone the project
----
git clone git@github.com:werval/werval-sample-beerdb.git
----

