= Skeletons
:jbake-type: page
:jbake-status: published
:jbake-tags: skeleton
:idprefix:
:toc: right
:toc-title: Catalog

Skeletons are simple git repositories that contains project templates for quick bootstrap of applications.
One doesn't need to install anything to use them except git.
Counterpart is that you will learn some git trickery along the way.

CAUTION: By their simple nature, skeletons are not dynamic at all.
There's no parameters nor templating involved.
If the community shout out and badly needs it we'll reconsider this choice.


toc::[]


== Choose a skeleton

Officially supported skeletons aim to cover frequent use cases.
They are for now limited to the following three types of applications: _HTTP Resources_, _WebApp_ and _Single Page Application_.
All skeletons have a Gradle and a Maven flavour.

[horizontal]
_HTTP Resources:: Lightweight application using only Werval's core and the JSON module or course
WebApp:: JSON resources and a server-side template engine
Single Page Application:: JSON resources and a client-side javascript application built using http://gulpjs.com/[gulp] & http://browserify.org/[browserify].

None of the skeletons include a persistence mechanism, you'll have to implement yours, see the available link:../doc/current/modules/index.html[modules].


== Gradle Skeletons


[IMPORTANT]
.Why use Subversion to download skeletons?
====
Github does not support `git archive` which is the equivalent of `svn export`.
Github provide a subversion view of git repositories, we're leveraging that.

`trunk` contains the `master` branch. You can list available branches and tags using `svn ls https://github.com/werval/werval-skel-gradle` for example.

A command line client for easy usage of application skeletons is under active discussion, planned and will be added in
a future release, see https://github.com/werval/werval/issues/99[#99].
====


=== HTTP Resources

See https://github.com/werval/werval-skel-gradle

----
svn export https://github.com/werval/werval-skel-gradle/trunk YOUR_APP_NAME
----

//=== WebApp
//
//See https://github.com/werval/werval-skel-gradle-web
//
//----
//svn export https://github.com/werval/werval-skel-gradle-web/trunk YOUR_APP_NAME
//----

=== Single Page Application

See https://github.com/werval/werval-skel-gradle-spa

----
svn export https://github.com/werval/werval-skel-gradle-spa/trunk YOUR_APP_NAME
----


== Maven Skeletons

=== HTTP Resources

See https://github.com/werval/werval-skel-maven

----
svn export https://github.com/werval/werval-skel-maven/trunk YOUR_APP_NAME
----

//=== WebApp
//
//See https://github.com/werval/werval-skel-web
//
//----
//svn export https://github.com/werval/werval-skel-maven-web/trunk YOUR_APP_NAME
//----
//
//=== Single Page Application
//
//See https://github.com/werval/werval-skel-maven-spa
//
//----
//svn export https://github.com/werval/werval-skel-maven-spa/trunk YOUR_APP_NAME
//----
